### PR TITLE
added workflow compatibility

### PR DESCRIPTION
**Pull request by tobias-trozowski**
[JENKINS-37068](https://issues.jenkins-ci.org/browse/JENKINS-37068)

```
node {
  step([$class: 'CloverPHPPublisher', cloverXml: 'clover-coverage.xml', reportDir: 'reports/', publishHtmlReport: 'true'])
}
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
ping @ssogabe . Can we merge this?

**Comment by sazo** [comment]
@ssogabe Really need this. :)

**Comment by matthieugauthier** [comment]
It works only if you call it with "cloverXml" and not with "xmlLocation" according the changements in code.
I've not try the html, i don't care about it :)

Thanks a lot about this contrib!!

`node {
  step([$class: 'CloverPHPPublisher', cloverXml: 'clover-coverage.xml'])
}`

**Comment by tobias-trozowski** [comment]
thanks @matthieugauthier i've updated my comment above.

**Comment by hlorofos** [comment]
@ssogabe are you alive?

**Comment by i-jk** [comment]
Thanks for the patch tobias-trozowski, hope it is merged soon... However, there's been no commits I can see since Nov 20, 2015, so it looks like this plugin has been abandoned... 

Does anyone know if the other Clover plugin (https://plugins.jenkins.io/clover) be used with any of the various `--coverage-XXX` outputs in PHPUnit?

Are there any other people there who could help?

I guess we have to patch our own plugins for now..

**Comment by marek-parfianowicz** [comment]
Hi, 

A [Clover plugin](https://plugins.jenkins.io/clover) developer here. I don't have write permissions to the CloverPHP plugin (both source code on GitHub and deployment of binaries), I'm afraid. 

I'd have to ask the Jenkins team for permissions. I'm a bit busy with developing the [OpenClover](http://openclover.org) though, so it may take a month or two until I'll manage to find time to test and merge CloverPHP changes. So it would be great if current plugin owner could merge it.

Implementation of the Workflow in Clover plugin is quite similar to the one in this pull request, you can see it here:
https://github.com/jenkinsci/clover-plugin/pull/14
https://github.com/jenkinsci/clover-plugin/pull/16

Cheers
Marek

**Comment by tobias-trozowski** [comment]
ping @ssogabe

**Comment by gimler** [comment]
@ssogabe ping

**Comment by Vasiliy-Lavrov** [comment]
ping @ssogabe

**Comment by jordisala1991** [comment]
Ping @marek-parfianowicz

**Comment by marek-parfianowicz** [comment]
Hi @jordisala1991, thanks for pinging me. I'm a watcher of this PR, but as I wrote on 12 Jun, I have no permissions to this repository (also no permissions to publish new binaries). So unfortunately I am unable to help, unless @ssogabe grants me permissions. 

The workaround I see: clone the repo, merge this PR and build the plugin on your workstation - you can always install a plugin by uploading a JAR file to Jenkins.

**Comment by jordisala1991** [comment]
Its sad, who else on jenkins could have permissions that we could ping? This is under jenkinsci organization

**Comment by marek-parfianowicz** [comment]
I suggest sending an email to jenkins developers mailing list.

**Comment by tobias-trozowski** [comment]
ping @ssogabe

**Review by pjona — APPROVED** [review]

**Comment by indera-shsp** [comment]
Can we please merge this?

**Comment by tobias-trozowski** [comment]
@indera-shsp seems like this fork is waaaaayyy to old.
see https://stackoverflow.com/questions/56595417/unable-to-compile-maven-project-in-jenkins-while-it-is-working-fine-in-the-eclip

**Comment by tobias-trozowski** [comment]
@alecharp seems you took over maintenance. any chance to get this PR merged?

**Pull request closed without merging**
